#!/bin/bash

usage() {
    echo "Usage: make-build [-mt]"
    echo "  -m: Only build main files"
    echo "  -t: Only build test files"
    exit 1
}

option_given=0

while getopts ":mt" opt; do
    option_given=1

    case $opt in
        m)
            cmake --build . --target CourseCompanion
            ;;
        t)
            cmake --build . --target AssignmentTests CourseTests TermTests CliViewTests \
                AssignmentControllerTests CourseControllerTests TermControllerTests \
                UtilsTests CourseAssignmentIntegrationTests TermCourseIntegrationTests \
                ControllerIntegrationTests
            ;;
        \?)
            echo "Invalid option: -$opt" >&2
            usage
            ;;
    esac
done

if [ $option_given -eq 0 ]; then
    cmake --build .
fi