#!/bin/bash

usage() {
    echo "Usage: setup-deps [-td]"
    echo "  -t: Output to build_test"
    echo "  -d: Output to build_test_db"
    exit 1
}

OS_NAME=$(uname)
option_given=0

if [[ "$OS_NAME" == "Darwin" ]]; then
    while getopts ":td" opt; do
        option_given=1

        case $opt in
            t)
                conan install .. --build=missing -of build_test -g CMakeDeps -g CMakeToolchain -s build_type=Release
                ;;
            d)
                conan install .. --build=missing -of build_test_db -g CMakeDeps -g CMakeToolchain -s build_type=Release
                ;;
            \?)
                echo "Invalid option: -$opt" >&2
                usage
                ;;
        esac
    done

    if [ $option_given -eq 0 ]; then
        # create toolchain file for build
        conan install .. --build=missing -of build_main -g CMakeDeps -g CMakeToolchain -s build_type=Release
    fi
elif [[ "$OS_NAME" == "Linux" ]]; then
    while getopts ":td" opt; do
        option_given=1

        case $opt in
            t)
                conan install ~/course-companion --build=missing -of build_test -g CMakeDeps -g CMakeToolchain -s build_type=Release
                ;;
            d)
                conan install ~/course-companion --build=missing -of build_test_db -g CMakeDeps -g CMakeToolchain -s build_type=Release
                ;;
            \?)
                echo "Invalid option: -$opt" >&2
                usage
                ;;
        esac
    done

    if [ $option_given -eq 0 ]; then
        # create toolchain file for build
        conan install ~/course-companion --build=missing -of build_main -g CMakeDeps -g CMakeToolchain -s build_type=Release
    fi
else
    echo "Unknown OS: $OS_NAME"
    exit 1
fi