#!/bin/bash

#!/bin/bash

usage() {
    echo "Usage: setup-deps [-t]"
    echo "  -t: Output to build_test"
}

option_given=0

while getopts ":t" opt; do
    option_given=1

    case $opt in
        t)
            conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_test
            ;;
        \?)
            echo "Invalid option: -$opt" >&2
            usage
            ;;
    esac
done

if [ $option_given -eq 0 ]; then
    # create toolchain file for build
    conan install /mnt/c/Users/Geoffrey/Documents/VS_Code/course-companion --build=missing -of build_main
fi